/**
 * Pull class invariants (and terminology constants they name) out of a BMM model.
 * Used by `tasks/generate_rm_meta.ts`. The catalogue is data; expressions stay
 * as published, including blanks.
 */

export interface BmmInvariantRow {
  schema: string;
  release: string;
  className: string;
  name: string;
  expression: string;
}

export interface BmmInvariantCatalogue {
  invariants: BmmInvariantRow[];
  constants: Record<string, string>;
}

interface BmmClassLike {
  name?: string;
  invariants?: Record<string, string>;
  constants?: Record<string, { value?: string }>;
}

interface BmmModelLike {
  schema_name?: string;
  rm_release?: string;
  class_definitions?: Record<string, BmmClassLike>;
  primitive_types?: Record<string, BmmClassLike>;
}

export function catalogueFromBmm(model: BmmModelLike): BmmInvariantCatalogue {
  const schema = model.schema_name ?? "";
  const release = model.rm_release ?? "";
  const invariants: BmmInvariantRow[] = [];
  const constants: Record<string, string> = {};

  const classes = {
    ...(model.primitive_types ?? {}),
    ...(model.class_definitions ?? {}),
  };

  for (const [key, cls] of Object.entries(classes)) {
    if (!cls || typeof cls !== "object") continue;
    const className = cls.name || key;
    if (cls.constants) {
      for (const [name, constant] of Object.entries(cls.constants)) {
        if (!constant || typeof constant.value !== "string") continue;
        constants[name] = unquoteBmmString(constant.value);
      }
    }
    if (!cls.invariants) continue;
    for (const [name, expression] of Object.entries(cls.invariants)) {
      invariants.push({
        schema,
        release,
        className,
        name,
        expression: expression ?? "",
      });
    }
  }

  invariants.sort((a, b) =>
    a.className === b.className
      ? a.name.localeCompare(b.name)
      : a.className.localeCompare(b.className)
  );
  return { invariants, constants };
}

export function emitBmmInvariantModule(
  catalogues: BmmInvariantCatalogue[],
): string {
  const invariants = catalogues.flatMap((c) => c.invariants);
  const constants: Record<string, string> = {};
  for (const catalogue of catalogues) {
    Object.assign(constants, catalogue.constants);
  }
  return `// Generated by tasks/generate_rm_meta.ts from the BMM URLs in tasks/bmm_versions.json.
// Do not edit by hand. Re-run \`deno task generate:rm-meta\`.

export interface BmmInvariantRow {
  schema: string;
  release: string;
  className: string;
  name: string;
  expression: string;
}

export const BMM_INVARIANTS: BmmInvariantRow[] = ${
    JSON.stringify(invariants, null, 2)
  };

export const BMM_CONSTANTS: Record<string, string> = ${
    JSON.stringify(constants, null, 2)
  };
`;
}

function unquoteBmmString(value: string): string {
  const trimmed = value.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}
