// openEHR LANG model — BMM package org.openehr.lang.bmm.core
// Generated by tasks/split_model_by_bmm_packages.ts from tasks/bmm_package_map.json.
// Package boundaries follow the BMM package structure; edit the class bodies here,
// but re-run the splitter rather than hand-moving declarations between packages.

import type { BMM_SIGNATURE, BMM_TYPE } from "../_shared.ts";
import * as openehr_base from "../../base/mod.ts";

/**
 * Abstract meta-type of BMM declared model elements. A _declaration_ is a an element of a model within a context, which defines the _scope_ of the element. Thus, a class definition and its property and routine definitions are model elements, but Types are not, since they are derived from model elements.
 */
export abstract class BMM_MODEL_ELEMENT {
  /**
   * Internal storage for name
   * @protected
   */
  protected _name?: openehr_base.String;

  /**
   * Name of this model element.
   */
  get name(): string | undefined {
    return this._name?.value;
  }

  /**
   * Gets the openehr_base.String wrapper object for name.
   * Use this to access openehr_base.String methods.
   */
  get $name(): openehr_base.String | undefined {
    return this._name;
  }

  /**
   * Sets name from either a primitive value or openehr_base.String wrapper.
   */
  set name(val: string | openehr_base.String | undefined) {
    if (val === undefined || val === null) {
      this._name = undefined;
    } else if (typeof val === "string") {
      this._name = openehr_base.String.from(val);
    } else {
      this._name = val;
    }
  }

  /**
   * Optional documentation of this element, as a keyed list.
   *
   * It is strongly recommended to use the following key /type combinations for the relevant purposes:
   *
   * * \`"purpose": String\`
   * * \`"keywords": List<String>\`
   * * \`"use": String\`
   * * \`"misuse": String\`
   * * \`"references": String\`
   *
   * Other keys and value types may be freely added.
   */
  documentation?: undefined;
  /**
   * Model element within which an element is declared.
   */
  scope?: BMM_MODEL_ELEMENT;
  /**
   * Optional meta-data of this element, as a keyed list. May be used to extend the meta-model.
   */
  extensions?: undefined;
  /**
   * True if this model element is the root of a model structure hierarchy.
   * @returns Result value
   */
  is_root_scope(): openehr_base.Boolean {
    // Root scope if there is no parent scope defined
    return openehr_base.Boolean.from(
      this.scope === undefined || this.scope === null,
    );
  }
}

/**
 * A formal element having a name, type and a type-based signature.
 */
export abstract class BMM_FORMAL_ELEMENT extends BMM_MODEL_ELEMENT {
  /**
   * Declared or inferred static type of the entity.
   */
  type?: BMM_TYPE;
  /**
   * Internal storage for is_nullable
   * @protected
   */
  protected _is_nullable?: openehr_base.Boolean;

  /**
   * True if this element can be null (Void) at execution time. May be interpreted as optionality in subtypes..
   */
  get is_nullable(): boolean | undefined {
    return this._is_nullable?.value;
  }

  /**
   * Gets the openehr_base.Boolean wrapper object for is_nullable.
   * Use this to access openehr_base.Boolean methods.
   */
  get $is_nullable(): openehr_base.Boolean | undefined {
    return this._is_nullable;
  }

  /**
   * Sets is_nullable from either a primitive value or openehr_base.Boolean wrapper.
   */
  set is_nullable(val: boolean | openehr_base.Boolean | undefined) {
    if (val === undefined || val === null) {
      this._is_nullable = undefined;
    } else if (typeof val === "boolean") {
      this._is_nullable = openehr_base.Boolean.from(val);
    } else {
      this._is_nullable = val;
    }
  }

  /**
   * Formal signature of this element, in the form:
   *
   * \`name [arg1_name: T_arg1, ...][:T_value]\`
   *
   * Specific implementations in descendants.
   * @returns Result value
   */
  signature(): BMM_SIGNATURE {
    return { name: this.name } as BMM_SIGNATURE;
  }

  /**
   * True if \`_type_\` is notionally Boolean (i.e. a \`BMM_SIMPLE_TYPE\` with \`_type_name()_\` = \`'Boolean'\`).
   * @returns Result value
   */
  is_boolean(): openehr_base.Boolean {
    // Check if type is a Boolean type
    if (!this.type) {
      return openehr_base.Boolean.from(false);
    }
    // Check type_name for "Boolean"
    const typeName = this.type.type_name ? this.type.type_name() : undefined;
    const typeNameStr = typeName?.value || String(typeName || "");
    return openehr_base.Boolean.from(
      typeNameStr.toLowerCase() === "boolean",
    );
  }
}
