/** Embedded symbol maps derived from symbol_table.yaml for browser + tests. */
/** Regenerate: deno run --allow-read --allow-write gen_symbol_table.ts */

export const SYMBOL_TABLE_LETTER_SYMBOLS = {
  "LOCATABLE.archetype_node_id": "id",
  "LOCATABLE.name": "na",
  "ARCHETYPED.archetype_id": "AX",
  "ARCHETYPED.template_id": "TP",
  "ARCHETYPED.rm_version": "rm",
  DV_BOOLEAN: "b",
  DV_IDENTIFIER: "id",
  DV_STATE: "st",
  DV_TEXT: "x",
  DV_CODED_TEXT: "c",
  DV_PARAGRAPH: "p",
  CODE_PHRASE: "C",
  TERM_MAPPING: "TM",
  DV_QUANTITY: "q",
  DV_COUNT: "co",
  DV_PROPORTION: "pr",
  DV_ORDINAL: "o",
  DV_INTERVAL: "iv",
  REFERENCE_RANGE: "RR",
  DV_DATE: "d",
  DV_TIME: "t",
  DV_DATE_TIME: "dt",
  DV_DURATION: "du",
  DV_MULTIMEDIA: "mu",
  DV_PARSABLE: "pa",
  DV_URI: "u",
  DV_EHR_URI: "eu",
  DV_SCALE: "sc",
  FEEDER_AUDIT: "FA",
  FEEDER_AUDIT_DETAILS: "FD",
  PARTY_PROXY: "PX",
  PARTY_IDENTIFIED: "PI",
  PARTY_RELATED: "PR",
  PARTY_SELF: "PS",
  PARTY_REF: "PF",
  OBJECT_REF: "OR",
  LOCATABLE_REF: "LR",
  OBJECT_VERSION_ID: "OV",
  PARTICIPATION: "PA",
  AUDIT_DETAILS: "AD",
  ATTESTATION: "AT",
  GENERIC_ID: "GX",
  INTERNET_ID: "IX",
  HIER_OBJECT_ID: "HX",
  UUID: "U",
  INTERVAL: "IV",
  ISM_TRANSITION: "IT",
  LINK: "LK",
  ITEM_SINGLE: "IS",
  ITEM_LIST: "IL",
  ITEM_TABLE: "TA",
  ITEM_TREE: "TR",
  CLUSTER: "CL",
  ELEMENT: "E",
  HISTORY: "HI",
  POINT_EVENT: "PE",
  INTERVAL_EVENT: "IE",
  EHR: "EH",
  EHR_STATUS: "ES",
  EHR_ACCESS: "EA",
  COMPOSITION: "CO",
  EVENT_CONTEXT: "EC",
  SECTION: "SE",
  ADMIN_ENTRY: "AE",
  OBSERVATION: "OB",
  EVALUATION: "EV",
  INSTRUCTION: "IN",
  ACTION: "AN",
  VERSIONED_OBJECT: "VO",
  CONTRIBUTION: "CB",
} as const;

export const SYMBOL_TABLE_EMOJI_SYMBOLS = {
  "LOCATABLE.archetype_node_id": "🆔",
  "LOCATABLE.name": "🪧",
  "ARCHETYPED.archetype_id": "Ⓐ",
  "ARCHETYPED.template_id": "Ⓣ",
  "ARCHETYPED.rm_version": "⚙️",
  DV_BOOLEAN: "🗹",
  DV_IDENTIFIER: "🪪",
  DV_STATE: "⚑",
  DV_TEXT: "🗉",
  DV_CODED_TEXT: "🗈",
  DV_PARAGRAPH: "🗎",
  CODE_PHRASE: "🏷️",
  TERM_MAPPING: "⇄",
  DV_QUANTITY: "🌡️",
  DV_COUNT: "🔢",
  DV_PROPORTION: "⨸",
  DV_ORDINAL: "📶",
  DV_INTERVAL: "↔️",
  REFERENCE_RANGE: "↕",
  DV_DATE: "📅",
  DV_TIME: "⌚",
  DV_DATE_TIME: "📅⌚",
  DV_DURATION: "⏳",
  DV_MULTIMEDIA: "📷",
  DV_PARSABLE: "🔣",
  DV_URI: "🔗",
  DV_EHR_URI: "⤮",
  DV_SCALE: "↕️",
  FEEDER_AUDIT: "📩",
  FEEDER_AUDIT_DETAILS: "📩🔍",
  PARTY_PROXY: "👤❔",
  PARTY_IDENTIFIED: "👤🪪",
  PARTY_RELATED: "👤🧑‍🧑‍🧒",
  PARTY_SELF: "👤👈",
  PARTY_REF: "↦👤",
  OBJECT_REF: "↦📦",
  LOCATABLE_REF: "↦🧭",
  OBJECT_VERSION_ID: "📦🆔",
  PARTICIPATION: "👥",
  AUDIT_DETAILS: "🛃🔍",
  ATTESTATION: "✍",
  GENERIC_ID: "🃏🆔",
  INTERNET_ID: "🖧🆔",
  HIER_OBJECT_ID: "🌳🆔",
  UUID: "🌌🆔",
  INTERVAL: "⟷",
  ISM_TRANSITION: "⏭",
  LINK: "⤭",
  ITEM_SINGLE: "🔸",
  ITEM_LIST: "▤",
  ITEM_TABLE: "▦",
  ITEM_TREE: "🌳",
  CLUSTER: "📁",
  ELEMENT: "🔹",
  HISTORY: "📉",
  POINT_EVENT: "🞋",
  INTERVAL_EVENT: "🔛",
  EHR: "🏥",
  EHR_STATUS: "🏥⏻",
  EHR_ACCESS: "🏥🔐",
  COMPOSITION: "🖂",
  EVENT_CONTEXT: "🛈",
  SECTION: "📚",
  ADMIN_ENTRY: "📝🧑‍💼",
  OBSERVATION: "👀",
  EVALUATION: "💭",
  INSTRUCTION: "💬",
  ACTION: "✅",
  VERSIONED_OBJECT: "🗃️",
  CONTRIBUTION: "📮",
} as const;

export type TerminologyShortcut = { readonly prefix: string; readonly emoji: string };
export const TERMINOLOGY_SHORTCUTS: readonly TerminologyShortcut[] = [
  { prefix: "openehr::", emoji: "🌬️" },
  { prefix: "local::", emoji: "📍" },
  { prefix: "ISO_639-1::", emoji: "🗪" },
  { prefix: "ISO_3166-1::", emoji: "🌐" },
  { prefix: "IANA_character-sets::", emoji: "🔤" },
] as const;

export type TerminologyFieldPromotion = {
  readonly field: string;
  readonly prefix: string;
  readonly emoji: string;
};
export const TERMINOLOGY_FIELD_PROMOTIONS: readonly TerminologyFieldPromotion[] = [
  { field: "language", prefix: "ISO_639-1::", emoji: "🗪" },
  { field: "territory", prefix: "ISO_3166-1::", emoji: "🌐" },
  { field: "encoding", prefix: "IANA_character-sets::", emoji: "🔤" },
] as const;
