/** Embedded copy of table3.yaml (first symbol per type) for Deno tests and browser bundle. */
/** Regenerate: deno run --allow-read --allow-write gen_table3_text.ts */
export default `
{
data_types: {
  archetype_node_id: ["🆔"],
  DV_BOOLEAN: ["✅"],
  DV_IDENTIFIER: ["🪪"],
  DV_STATE: ["⚑"],
  DV_TEXT: ["🗉"],
  DV_CODED_TEXT: ["🗈"],
  DV_PARAGRAPH: ["📃"],
  CODE_PHRASE: ["🏷️"],
  TERM_MAPPING: ["🔀"],
  DV_QUANTITY: ["🌡️"],
  DV_COUNT: ["🔢"],
  DV_PROPORTION: ["⨸"],
  DV_ORDINAL: ["📶"],
  DV_INTERVAL: ["↔️"],
  REFERENCE_RANGE: ["↕"],
  DV_DATE: ["📅"],
  DV_TIME: ["⌚"],
  DV_DATE_TIME: ["📅⌚"],
  DV_DURATION: ["⏳"],
  DV_MULTIMEDIA: ["📷"],
  DV_PARSABLE: ["🔣"],
  DV_URI: ["🔗"],
  DV_EHR_URI: ["⤨"],
  DV_SCALE: ["↕️"],
  FEEDER_AUDIT: ["📩"],
  FEEDER_AUDIT_DETAILS: ["📥🔍"],
  PARTY_PROXY: ["👤❔"],
  PARTY_IDENTIFIED: ["👤🪪"],
  PARTY_SELF: ["👤👈"],
  PARTY_REF: ["👤⤨"],
  PARTY_RELATED: ["👤🧑‍🧑‍🧒"],
}, data_structures: {
  ITEM_SINGLE: ["🔸"],
  ITEM_LIST: ["▤"],
  ITEM_TABLE: ["▦"],
  ITEM_TREE: ["🌳"],
  CLUSTER: ["📁"],
  ELEMENT: ["🔹"],
  HISTORY: ["📉"],
  POINT_EVENT: ["🞋"],
  INTERVAL_EVENT: ["⟷"],
}, ehr_components: {
  EHR: ["🏥"],
  EHR_STATUS: ["🏥⏻"],
  EHR_ACCESS: ["🏥🔐"],
  COMPOSITION: ["🖂"],
  EVENT_CONTEXT: ["🛈"],
  SECTION: ["📚"],
  ADMIN_ENTRY: ["📝🧑‍💼"],
  OBSERVATION: ["👀"],
  EVALUATION: ["💭"],
  INSTRUCTION: ["❏"],
  ACTION: ["🗹"],
  VERSIONED_OBJECT: ["🗃️"],
  CONTRIBUTION: ["📮"],
}, terminology_shortcuts: {
  openehr: ["🌬️"],
  local: ["📍"],
  language: ["💬"],
  territory: ["🌐"],
  encoding: ["🔤"],
}, field_promotions: {
  language: ["💬"],
  territory: ["🌐"],
  encoding: ["🔤"],
}, foundation_types: {
} }
` as string;
