/**
 * Generator tests for specification-description tables (no network).
 */
import { assertEquals } from "https://deno.land/std@0.220.0/assert/mod.ts";
import {
  buildSpecDocsTables,
  emitSpecDocsTypeScript,
} from "../../../tasks/spec_docs_generator.ts";
import type { BmmModel } from "../../../tasks/bmm_parser.ts";

Deno.test("buildSpecDocsTables copies BMM docs and classes.json HTML/MD URLs", () => {
  const model = {
    class_definitions: {
      DV_QUANTITY: {
        name: "DV_QUANTITY",
        documentation: "Measurable quantity.",
        properties: {
          magnitude: {
            _type: "P_BMM_SINGLE_PROPERTY",
            name: "magnitude",
            documentation: "Numeric magnitude.",
            type: "Real",
          },
          units: {
            _type: "P_BMM_SINGLE_PROPERTY",
            name: "units",
            type: "String",
          },
        },
      },
    },
  } as unknown as BmmModel;

  const tables = buildSpecDocsTables(
    [{
      packageKey: "openehr_rm",
      model,
      source: "mem://openehr_rm",
    }],
    {
      classes: [{
        name: "DV_QUANTITY",
        component: "RM",
        specification: "data_types",
        fragment: "_dv_quantity_class",
        link: "/releases/RM/development/data_types.html#_dv_quantity_class",
      }],
    },
    "2026-09-04T00:00:00.000Z",
  );

  assertEquals(tables.classes.length, 1);
  const row = tables.classes[0];
  assertEquals(row.name, "DV_QUANTITY");
  assertEquals(row.component, "RM");
  assertEquals(row.documentation, "Measurable quantity.");
  assertEquals(row.attributes, [{
    name: "magnitude",
    documentation: "Numeric magnitude.",
  }]);
  assertEquals(
    row.specHtmlUrl,
    "https://specifications.openehr.org/releases/RM/development/data_types.html#_dv_quantity_class",
  );
  assertEquals(
    row.specMarkdownUrl,
    "https://specifications.openehr.org/releases/RM/development/data_types.md#_dv_quantity_class",
  );

  const ts = emitSpecDocsTypeScript(tables);
  assertEquals(ts.includes("DO NOT EDIT THIS FILE DIRECTLY"), true);
  assertEquals(ts.includes("DV_QUANTITY"), true);
});

Deno.test("buildSpecDocsTables synthesizes AOM 1.4 HTML when classes.json link is empty", () => {
  const model = {
    class_definitions: {
      C_QUANTITY: {
        name: "C_QUANTITY",
        documentation: "Constrainer class for Quantity data.",
      },
    },
  } as unknown as BmmModel;

  const tables = buildSpecDocsTables(
    [{ packageKey: "openehr_am", model, source: "mem://am" }],
    {
      classes: [{
        name: "C_QUANTITY",
        component: "AM",
        specification: "aom14",
        fragment: "_c_quantity_class",
        link: "",
      }],
    },
  );

  assertEquals(
    tables.classes[0].specHtmlUrl,
    "https://specifications.openehr.org/releases/AM/development/AOM1.4.html#_c_quantity_class",
  );
  assertEquals(
    tables.classes[0].specMarkdownUrl,
    "https://specifications.openehr.org/releases/AM/development/AOM1.4.md#_c_quantity_class",
  );
});

Deno.test("buildSpecDocsTables keeps classes.json URL-only rows missing from BMM", () => {
  const tables = buildSpecDocsTables(
    [{
      packageKey: "openehr_rm",
      model: { class_definitions: {} } as unknown as BmmModel,
      source: "mem://rm",
    }],
    {
      classes: [{
        name: "C_QUANTITY",
        component: "AM",
        specification: "aom14",
        fragment: "_c_quantity_class",
        link: "",
      }],
    },
  );
  assertEquals(tables.classes.length, 1);
  assertEquals(tables.classes[0].name, "C_QUANTITY");
  assertEquals(tables.classes[0].component, "AM");
  assertEquals(tables.classes[0].attributes, []);
  assertEquals(
    tables.classes[0].specHtmlUrl,
    "https://specifications.openehr.org/releases/AM/development/AOM1.4.html#_c_quantity_class",
  );
});
